### ISSUE TITLE
How to link database?

### ISSUE THREAD

**Issue by fabiomorreale** [sergius02/ulauncher-unotion#3]
Hey there, this extension looks exactly what I need but I can't make it work.

On Notion, I created a database that contains the property "Tags" and have created a new integration. However, I am not sure how to link the integration to that specific database. I can only indicate the Notion workspace, not a database within it.

Thanks!

**Comment by sergius02** [comment]
Hi!

You need to click on "Share" and then select your integration. I've made some screenshots:

![unotion1](https://user-images.githubusercontent.com/10380412/150386500-2cb65ef8-9f7b-4892-b42e-4cc6a8d1f09e.png)
![unotion2](https://user-images.githubusercontent.com/10380412/150386511-046b20f9-65a2-4d8e-845c-ccdf905767ca.png)

**Comment by fabiomorreale** [comment]
It worked! Thanks so much, Sergio.
